# Generated by Django 4.0.5 on 2022-07-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_rename_auctoin_bid_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
