# Generated by Django 4.0.3 on 2022-07-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_alter_bid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
