# Generated by Django 4.0.3 on 2022-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auction',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='auction',
            name='participants_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='show_best_bid',
            field=models.BooleanField(default=False),
        ),
    ]
