# Generated by Django 4.0.3 on 2022-05-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_auction_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tags',
            table=None,
        ),
    ]
