# Generated by Django 4.0.3 on 2022-06-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0002_rename_auctoin_bid_auction"),
        ("auction", "0004_alter_auction_table_alter_category_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="best_bid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="best_bid",
                to="bid.bid",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="celery_task_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
