# Generated by Django 4.0.3 on 2022-07-08 15:22

import auction.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0002_rename_auctoin_bid_auction"),
        ("auction", "0006_alter_auction_best_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="auction_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=auction.models.photo_path
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="best_bid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="best_bid",
                to="bid.bid",
            ),
        ),
    ]
