# Generated by Django 4.0.5 on 2022-07-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_auction_image_alter_auction_best_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
