# Generated by Django 4.0.3 on 2022-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auction_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='tags',
        ),
        migrations.AddField(
            model_name='auction',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
