# Generated by Django 4.0.3 on 2022-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_remove_auction_tags_auction_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='tags',
        ),
        migrations.AddField(
            model_name='auction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='auction.tags'),
        ),
    ]
